### ISSUE TITLE
Троянские программы

### ISSUE THREAD

**Issue by fackir** [dunvit/EveJima#2]
[http://prntscr.com/mz1ajg](url)
это с чем едят?
Malwarebytes
www.malwarebytes.com

-Данные журнала-
Дата события защиты: 17.03.2019
Время события защиты: 16:00
Файл журнала: 92947f9e-48b4-11e9-99b7-005056c00001.json

-Информация о ПО-
Версия: 3.7.1.2839
Версия компонентов: 1.0.538
Версия пакета обновления: 1.0.9722
Лицензия: Ознакомительная версия

-Информация о системе-
ОС: Windows 10 (Build 17763.379)
Процессор: x64
Файловая система: NTFS
Пользователь: System

-Сведения о заблокированном веб-сайте-
Вредоносный веб-сайт: 1
, , Заблокировано, [-1], [-1],0.0.0

-Информация о веб-сайте-
Категория: Троянские программы
Домен: www.evajima-storage.somee.com
IP-адрес: 66.85.73.159
Порт: [9108]
Тип: Исходящий трафик
Файл: D:\games\eve\soft\EveJima.2.28\EveJima\EveJima.exe

Объясните  зачем программа лезет на выше указанный адрес

**Comment by dunvit** [comment]
На сайте www.evajima-storage.somee.com лежат метрики.
